let cart=[];let selected=[];
function money(n){return "₹"+Number(n).toFixed(2)}
function renderProducts(){document.getElementById("products").innerHTML=products.map((p,i)=>`<article class="product"><div class="product-img">Gift<br>Customize</div><div class="product-body"><span class="badge">50% OFF</span><h3>${p[0]}</h3><p>${p[3]} • Personalized gifting</p><div class="price"><span class="old">${money(p[1])}</span><b class="sale">${p[2]}</b></div><button class="btn dark" onclick="addProduct(${i})">Add to Cart</button></div></article>`).join("")}
function renderCustom(){document.getElementById("customGrid").innerHTML=customItems.map((x,i)=>`<div class="custom-item ${selected.includes(i)?"selected":""}" onclick="toggleCustom(${i})"><div class="custom-photo">${x[0]}</div><b>${x[1]}</b><small>Eligible for ₹599 hamper</small></div>`).join("");document.getElementById("selectedText").textContent=`${selected.length} / 4 selected`;document.getElementById("selectedItems").textContent=selected.length?selected.map(i=>customItems[i][1]).join(", "):"No items selected";document.getElementById("customCart").disabled=selected.length!==4}
function toggleCustom(i){if(selected.includes(i))selected=selected.filter(x=>x!==i);else if(selected.length<4)selected.push(i);renderCustom()}
function addProduct(i){cart.push({name:products[i][0],price:parseFloat(products[i][2].replace("₹",""))});updateCart();openCart()}
function addCustomToCart(){if(selected.length!==4)return;cart.push({name:"Build Your Own Hamper — Any 4 Items",price:599,items:selected.map(i=>customItems[i][1])});selected=[];renderCustom();updateCart();openCart()}
function updateCart(){document.getElementById("cartCount").textContent=cart.length;document.getElementById("cartItems").innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-row"><span>${x.name}${x.items?`<small style="display:block;color:#888">${x.items.join(" • ")}</small>`:""}</span><b>${money(x.price)}</b></div>`).join(""):`<p class="muted">Your cart is empty.</p>`;document.getElementById("cartTotal").textContent=money(cart.reduce((s,x)=>s+x.price,0))}
function openCart(){document.getElementById("cartModal").style.display="block";updateCart()}function closeCart(){document.getElementById("cartModal").style.display="none"}
function checkout(){if(!cart.length){alert("Please add a product first.");return}alert("Checkout foundation is ready. Next step: connect the QR payment and order-management backend.")}
renderProducts();renderCustom();updateCart();